import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import VerticalMenu from "@/components/DropDownMenu/VerticalMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
        rel="stylesheet"
      /> */}
      <body className={inter.className + " flex flex-col w-full"}>
        <div
          //banner height 200px
          className="bg-slate-900  w-full flex justify-start items-center h-96 border-b-2 border-slate-800"
        >
          <h1 className="text-2xl font-bold ml-20 py-4 text-blue-300">
            Cliente CS3
          </h1>
        </div>
        <div className="bg-slate-900 w-full  flex ">
          <div className="w-1/6 min-w-64  h-screen border-r-2 border-slate-800 ">
            <VerticalMenu />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
